/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ViewPublicImport } from './routes/_view-public'
import { Route as ViewIndexImport } from './routes/_view-index'
import { Route as ViewAuthenticateImport } from './routes/_view-authenticate'
import { Route as ViewAdminImport } from './routes/_view-admin'
import { Route as ViewPublicCommunitiesIndexImport } from './routes/_view-public/communities/index'
import { Route as ViewPublicCommunitiesProfileIndexImport } from './routes/_view-public/communities/$profile/index'
import { Route as ViewPublicCommunitiesProfileTypeIndexImport } from './routes/_view-public/communities/$profile/$type/index'

// Create Virtual Routes

const ViewIndexIndexLazyImport = createFileRoute('/_view-index/')()

// Create/Update Routes

const ViewPublicRoute = ViewPublicImport.update({
  id: '/_view-public',
  getParentRoute: () => rootRoute,
} as any)

const ViewIndexRoute = ViewIndexImport.update({
  id: '/_view-index',
  getParentRoute: () => rootRoute,
} as any)

const ViewAuthenticateRoute = ViewAuthenticateImport.update({
  id: '/_view-authenticate',
  getParentRoute: () => rootRoute,
} as any)

const ViewAdminRoute = ViewAdminImport.update({
  id: '/_view-admin',
  getParentRoute: () => rootRoute,
} as any)

const ViewIndexIndexLazyRoute = ViewIndexIndexLazyImport.update({
  path: '/',
  getParentRoute: () => ViewIndexRoute,
} as any).lazy(() =>
  import('./routes/_view-index/index.lazy').then((d) => d.Route),
)

const ViewPublicCommunitiesIndexRoute = ViewPublicCommunitiesIndexImport.update(
  {
    path: '/communities/',
    getParentRoute: () => ViewPublicRoute,
  } as any,
)

const ViewPublicCommunitiesProfileIndexRoute =
  ViewPublicCommunitiesProfileIndexImport.update({
    path: '/communities/$profile/',
    getParentRoute: () => ViewPublicRoute,
  } as any)

const ViewPublicCommunitiesProfileTypeIndexRoute =
  ViewPublicCommunitiesProfileTypeIndexImport.update({
    path: '/communities/$profile/$type/',
    getParentRoute: () => ViewPublicRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_view-admin': {
      preLoaderRoute: typeof ViewAdminImport
      parentRoute: typeof rootRoute
    }
    '/_view-authenticate': {
      preLoaderRoute: typeof ViewAuthenticateImport
      parentRoute: typeof rootRoute
    }
    '/_view-index': {
      preLoaderRoute: typeof ViewIndexImport
      parentRoute: typeof rootRoute
    }
    '/_view-public': {
      preLoaderRoute: typeof ViewPublicImport
      parentRoute: typeof rootRoute
    }
    '/_view-index/': {
      preLoaderRoute: typeof ViewIndexIndexLazyImport
      parentRoute: typeof ViewIndexImport
    }
    '/_view-public/communities/': {
      preLoaderRoute: typeof ViewPublicCommunitiesIndexImport
      parentRoute: typeof ViewPublicImport
    }
    '/_view-public/communities/$profile/': {
      preLoaderRoute: typeof ViewPublicCommunitiesProfileIndexImport
      parentRoute: typeof ViewPublicImport
    }
    '/_view-public/communities/$profile/$type/': {
      preLoaderRoute: typeof ViewPublicCommunitiesProfileTypeIndexImport
      parentRoute: typeof ViewPublicImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  ViewIndexRoute.addChildren([ViewIndexIndexLazyRoute]),
  ViewPublicRoute.addChildren([
    ViewPublicCommunitiesIndexRoute,
    ViewPublicCommunitiesProfileIndexRoute,
    ViewPublicCommunitiesProfileTypeIndexRoute,
  ]),
])

/* prettier-ignore-end */
